env: 'local' # dev, prod
storage_path: '../../storage/myStore.db'

http_server:
  address: 'localhost:8090'
  timeout: 4s
  idle_timeout: 60s

auth:
  jwt:
    jwt_secret: '12ncvx23ncd94JS'
    token_expiration: 24h
